apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-toolbox.fullname" . }}
  labels:
    {{- include "postgres-toolbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres-toolbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres-toolbox.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres-toolbox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: key-volume
          secret:
            secretName: {{ .Values.serviceAccountKey }}
        - name: toolbox-scripts
          configMap:
            name: {{ .Release.Name }}-scripts
            defaultMode: 0777
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PGPASSFILE
              value: "/root/.pgpass"
            - name: DB_CLUSRER_NAME
              value: "{{ .Values.db.name }}"
            - name: DB_NAME
              value: "{{ .Values.db.name }}"
            - name: GS_BUCKET
              value: "{{ .Values.db.gs_backup_bucket }}"
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db_user
            - name: "DB_PW"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db_password
          command:
            - "bash"
            - "-c"
            - | 
              /scripts/gcp-login.sh
              /scripts/gen-pg-config.sh
              
              echo "Toolbox container, login with kubectl to operate"
              
              tail -f /dev/null
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/google/security
              name: key-volume
            - mountPath: /scripts
              name: toolbox-scripts
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
