apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-toolbox.fullname" . }}
  labels:
    {{- include "postgres-toolbox.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres-toolbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "postgres-toolbox.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "postgres-toolbox.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: key-volume
          secret:
            secretName: {{ .Values.serviceAccountKey }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "bash"
            - "-c"
            - | 
              set -eu -o pipefail
              set -x
              gcloud auth activate-service-account --key-file /etc/google/security/*.json

              export DB_NAME=potato666
              export DB_USER=potatouser
              export DB_PW=potato123
              
              cat > ~/.pgpass <<EOF
              *:*:${DB_NAME}:${DB_USER}:${DB_PW}
              EOF
              chmod 0600 ~/.pgpass
              export PGPASSFILE=~/.pgpass


              echo "Toolbox container, login with kubectl to operate"
              
              tail -f /dev/null
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/google/security
              name: key-volume
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
