apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres-init.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "postgres-init.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
