apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-db-creation
  labels:
    {{- include "postgres-init.labels" . | nindent 4 }}
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "postgres-init.serviceAccountName" . }}
      volumes:
        - name: db-dumps
          configMap:
            name: {{ .Release.Name }}-db-dump
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-scripts
            defaultMode: 0777
      containers:
        - name: db-creation
          image: {{ .Values.dbCreation.image.repository }}:{{ .Values.dbCreation.image.tag }}
          imagePullPolicy: {{ .Values.dbCreation.image.pullPolicy }}
          env:
            - name: DUMP_FILES
              value: "/db-dumps/*"
            - name: DB_NS
              value: "pgo"
            - name: PGPASSFILE
              value: "~/.pgpass"
            - name: DB_CLUSRER_NAME
              value: "{{ .Values.db.name }}"
            - name: DB_NAME
              value: "{{ .Values.db.name }}"
            - name: PG_REPLICAS
              value: "{{ .Values.db.replicas }}"
            - name: PGBOUNCER_REPLICAS
              value: "{{ .Values.db.pgbouncer }}"
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db_user
            - name: "DB_PW"
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-secret
                  key: db_password
          command:
            - "bash"
            - "-c"
            - | 
              set -eu -o pipefail
              set -x
              /scripts/db-init.sh
          resources:
            {{- toYaml .Values.dbCreation.resources | nindent 12 }}
          volumeMounts:
            - name: db-dumps
              mountPath: "/db-dumps"
            - mountPath: /scripts
              name: scripts
      {{- with .Values.dbCreation.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
