apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-dump
  labels:
    {{- include "postgres-init.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "db-dump/*").AsConfig | indent 2 }}