apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "postgres-init.labels" . | nindent 4 }}
data:
  db_user: {{ .Values.db.user | b64enc }}
  db_password: {{ .Values.db.password | b64enc }}
