image:
  repository: "denis256/toolbox"
  tag: "0.0.2"

db:
  name: "${db_name}"
  user: "${db_user}"
  password: "${db_password}"
  gs_backup_bucket: "${gs_backup_bucket}"


cronjob:
  image:
    repository: "denis256/toolbox"
    tag: "0.0.2"
  schedule: "${db_backup_schedule}"
