image:
  repository: "${image_toolbox_repository}"
  tag: "${image_toolbox_tag}"

db:
  name: "${db_name}"
  user: "${db_user}"
  password: "${db_password}"
  gs_backup_bucket: "${gs_backup_bucket}"


cronjob:
  image:
    repository: "${image_toolbox_repository}"
    tag: "${image_toolbox_tag}"
  schedule: "${db_backup_schedule}"

tolerations:
  - key: app
    value: postgres
    effect: "NoSchedule"

