dbCreation:
  image:
    repository: "${image_toolbox_repository}"
    tag: "${image_toolbox_tag}"

db:
  name: "${db_name}"
  user: "${db_user}"
  password: "${db_password}"
  replicas: "${db_replicas}"
  pgbouncer: "${db_pgbouncer}"