name: "${name}"

rbac:
    useClusterAdmin: true


pgo_client_container_install: "true"
pgo_cluster_admin: "true"

pod_anti_affinity: "required"
pod_anti_affinity_pgbackrest: "required"
pod_anti_affinity_pgbouncer: "required"

tolerations:
  - key: app
    value: postgres
    effect: "NoSchedule"
