dbCreation:
  image:
    repository: "denis256/toolbox"
    tag: "0.0.2"

db:
  name: "${db_name}"
  user: "${db_user}"
  password: "${db_password}"
  replicas: "${db_replicas}"
  pgbouncer: "${db_pgbouncer}"